name = "wocus"
main = "./dist/_worker.js/chunks/runtime.mjs"
workers_dev = false
#account_id = ""
#route = ""
compatibility_date = "2024-03-18"
#compatibility_flags = [ "nodejs_compat" ]
send_metrics = false

[site]
bucket = "dist"
