name = "wocus"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2023-12-01"
account_id = ""
route = ""
compatibility_flags = [ "nodejs_compat" ]
send_metrics = false

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

[site]
bucket = ".output/public"
