name: wocus deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup PNPM
      uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install
      run: pnpm install
    - name: Build
      run: pnpm run build
    - name: Deploy
      run: echo "$SSH_KEY" > ${{ runner.temp }}/key && chmod 600 ${{ runner.temp }}/key
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
    - name: Deploy with rsync
      run: rsync -ahv --delete -e "ssh -i ${{ runner.temp }}/key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${SSH_PORT}" ${GITHUB_WORKSPACE}/.output ${SSH_USER}@${SSH_HOST}:${SSH_PATH}
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_PATH: ${{ secrets.SSH_PATH }}
